---
abstract: 'Some useful pointer utilities when writing FFI modules'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Module::Build: '0.4005'
  Test::More: '0'
configure_requires:
  ExtUtils::CChecker: '0'
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: FFI-Util
requires:
  Exporter::Tidy: '0'
  FFI::Raw: '0.27'
  Math::Int64: '0'
  Module::Build: '0.4005'
  base: '0'
  perl: v5.10.0
resources:
  bugtracker: https://github.com/plicease/ffi-util/issues
  homepage: http://perl.wdlabs.com/FFI-Util/
  repository: git://github.com/plicease/ffi-util.git
version: '0.03'
